name = "LookingGlass"
uuid = "1fcbbee2-b350-4a01-aad8-439064dba09e"
authors = ["Nathan Daly"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
